How to treat an error inside the try using only one catch?
